### ISSUE TITLE
Should find_package(Range REQUIRED) be replaced with find_package(range-v3 REQUIRED) ?

### ISSUE THREAD

**Issue by gartung** [art-framework-suite/canvas#1]
In the spack Icaruscode environment, `find_package(Range REQUIRED)` caused an error because cetmodules/Modules/FindRange.cmake was not included directly, only as a build dependency. The `range` package in spack provides findrange-v3.cmake instead.
Should find_package(Range REQUIRED) be replaced with find_package(range-v3 REQUIRED) at the location linked below
https://github.com/art-framework-suite/canvas/blob/bdfcdcebcc1c8f802334ae3d0bb137e883879bc7/canvas/CMakeLists.txt#L6

**Comment by chissg** [comment]
After some investigation, it appears that the CMake config files were unintentionally omitted from the UPS packages due to being installed in an unexpected place: `lib` for an architecture-independent package. I will update the UPS packaging of the latest version of Range-v3 to correct this, and provide appropriate CMake code in cetmodules to allow correct handling of deficient UPS packages, corrected UPS packages and non-UPS packages.

**Comment by chissg** [comment]
Go ahead and patch for Spack, @gartung, and I will make the necessary adjustments to cetmodules such that the change can be made to the main repository.

**Comment by chissg** [comment]
Acutally @gartung, technically it should be:
```.cmake
find_package(Range-v3 REQUIRED)
```
The project name is `Range-v3`. Find config files of the form `*-config.cmake` are lower-case, whereas `Find*.cmake` and `*Config.cmake` should match the project name for case.

**Comment by gartung** [comment]
OK. I was going by the *Config.cmake file
```
pwd
/scratch/gartung/spack/opt/spack/linux-scientific7-x86_64/gcc-9.3.0/range-v3-0.11.0-4o7pihlfaxmks5zpsjsczue3y4emup5s/lib/cmake/range-v3
-bash-4.2$ ls 
range-v3-config.cmake  range-v3-config-version.cmake  range-v3-targets.cmake
```

**Comment by gartung** [comment]
@chissg I see that FindRange.cmake was remove from cetmodules@2.29.10. This breaks the build of canvas@3.12.04. Should FindRange.cmake be kept as a wrapper for find_package(Range-v3)?

**Comment by gartung** [comment]
Nevermind. I see that you mentioned moving it to compat/FindRange.cmake.

**Comment by gartung** [comment]
As of cetmodules@2.29.13 changing Range to range-v3 is not needed in the Spack environment.
